name: Lambda CI

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'
      - '.github/workflows/lambda-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lambda/**'
      - '.github/workflows/lambda-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install Image Processor dependencies
      working-directory: lambda/image-processor
      run: |
        npm ci
        npm run test
    
    - name: Install Notification Handler dependencies
      working-directory: lambda/notification-handler
      run: |
        npm ci
        npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install and run ESLint
      run: |
        npm install eslint eslint-config-airbnb-base eslint-plugin-import --save-dev
        npx eslint lambda/image-processor/
        npx eslint lambda/notification-handler/

  security:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high 