name: Lambda CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'
      - '.github/workflows/lambda-ci.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    paths:
      - 'lambda/**'
      - '.github/workflows/lambda-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        function: [image-processor, notification-handler]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
      
    - name: Install function dependencies
      working-directory: lambda/${{ matrix.function }}
      run: npm install
    
    - name: Run tests
      working-directory: lambda/${{ matrix.function }}
      run: npm test
      
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-${{ matrix.function }}
        path: lambda/${{ matrix.function }}/coverage
        retention-days: 14

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [image-processor, notification-handler]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm install
      
    - name: Install function dependencies
      working-directory: lambda/${{ matrix.function }}
      run: npm install
    
    - name: Run ESLint
      working-directory: lambda/${{ matrix.function }}
      run: npm run lint

  security:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd lambda/image-processor && npm install
        cd ../notification-handler && npm install
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        command: test

  release:
    needs: [security]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        configuration: ".github/changelog-config.json"
        commitMode: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{steps.changelog.outputs.changelog}}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          LICENSE
          README.md 